main: ${mainClass}
name: ${name}
version: ${version}
api-version: 1.13
depend: [Vault]
author: royalkingkb

commands:
  list:
    description: List players on the server
    aliases: [l, who, online, glist, globallist, listeveryonewhoisontheserver, whosonline]
  vanish:
    description: Vanish from other players
    permission: ruinscraft.command.vanish
  mblist:
    description: Legacy command
    permission: ruinscraft.command.mblist
