main: ${mainClass}
name: ${name}
version: ${version}

depend: [Vault]

commands:
  list:
    description: List players on the server
    aliases: [l, who, online, glist, globallist, listeveryonewhoisontheserver, whosonline]
  vanish:
    description: Vanish from other players
    aliases: [v, van]
    permission: ruinscraft.command.vanish